from __future__ import annotations


INTERNAL_KEYS = {
    "id",
    "import_key",
    "source_id",
    "chunk_id",
    "evidence",
    "embedding",
    "embedding_text",
    "aliases",
    "vector_score",
    "lexical_score",
    "rrf_score",
    "score",
    "retrieval_sources",
    "vector_rank",
    "lexical_rank",
    "ranking_score_raw",
    "matched_shingles",
    "selection_reason",
    "selection_reasons",
    "owner_labels",
}

DISPLAY_KEYS = {
    "p.name": "Parking",
    "c.name": "Campus",
    "campus_name": "Campus",
    "parking_name": "Parking",
    "course_name": "Course",
    "contact": "Contact",
    "service": "Service",
    "preparatory_program": "Preparatory program",
    "document": "Document",
    "required_for": "Required for",
    "prepares_for": "Prepares for",
    "facility_note": "Facility evidence note",
    "from": "From",
    "to": "To",
    "program": "Program",
    "program_name": "Program",
    "faculty": "Faculty",
    "owner": "Owner",
    "requirement": "Requirement",
    "requirement_text": "Requirement text",
    "description": "Description",
    "fee": "Fee",
    "relationship": "Relationship details",
    "relation": "Relation",
    "specialization": "Specialization",
    "policy": "Policy",
    "policy_type": "Policy type",
    "scholarship": "Scholarship",
    "course": "Course",
    "housing": "Housing",
    "unit_type": "Housing unit type",
    "parking": "Parking",
    "campus": "Campus",
    "focus": "Focus",
    "name": "Name",
    "clarification": "Clarification",
    "location": "Location",
    "address": "Address",
    "phone": "Phone",
    "email": "Email",
    "whatsapp": "WhatsApp",
    "fax": "Fax",
    "office_hours": "Office hours",
    "duration": "Duration",
    "tuition_type": "Tuition type",
    "credits": "Credits",
    "study_days": "Study days",
    "study_format": "Study format",
    "career_fields": "Career fields",
    "amount_value": "Amount",
    "display_amount": "Amount",
    "currency": "Currency",
    "amount_unit": "Amount unit",
    "payment_context": "Payment context",
    "payment_condition": "Payment condition",
    "discount_percent": "Percent reduction",
    "valid_until": "Valid until",
    "fee_type": "Fee type",
    "deadline": "Deadline",
    "conditions": "Conditions",
    "academic_year": "Academic year",
    "requirement_type": "Requirement type",
    "criteria_logic": "Criteria logic",
    "bagrut_average_min": "Minimum bagrut average",
    "psychometric_min": "Minimum psychometric score",
    "combined_score_min": "Minimum combined score",
    "math_units": "Math units",
    "math_grade_min": "Minimum math grade",
    "physics_units": "Physics units",
    "physics_grade_min": "Minimum physics grade",
    "hebrew_score_min": "Minimum Hebrew score",
    "alternative_bagrut_average_min": "Minimum alternative bagrut average",
    "alternative_psychometric_min": "Minimum alternative psychometric score",
    "alternative_math_units": "Alternative math units",
    "alternative_math_grade_min": "Minimum alternative math grade",
    "open_university_credits_min": "Minimum Open University credits",
    "rule_text": "Rule",
    "deadline_relation": "Deadline relation",
    "monthly_rent": "Monthly rent",
    "monthly_total": "Monthly total",
    "english_exam": "English exam",
    "mimd_score_min": "Minimum MIMD score",
    "matam_score_min": "Minimum MATAM score",
    "gre_psychology_min": "Minimum GRE psychology score",
    "engineer_exam_avg_min": "Minimum external exam average",
    "engineer_studies_avg_min": "Minimum engineering-studies average",
    "degree_avg_min": "Minimum degree average",
    "required": "Required",
    "occupants": "Occupants",
    "course_category": "Course category",
    "semester": "Semester",
    "year": "Year",
    "weekly_hours": "Weekly hours",
    "exemption_type": "Exemption type",
    "exam_date": "Exam date",
    "exam_time": "Exam time",
}

ROW_ALIAS_KEYS = {
    "p.name": "parking",
    "c.name": "campus",
    "campus_name": "campus",
    "parking_name": "parking",
    "course_name": "course",
    "ProgramName": "program",
    "SpecializationName": "specialization",
    "Description": "description",
    "Focus": "focus",
}

ENTITY_PUBLIC_FIELDS = {
    "Program": ["name", "english_name", "degree_type", "duration", "credits", "study_days", "study_format", "tuition_type", "career_fields", "description"],
    "ContactPoint": ["name", "phone", "email", "whatsapp", "office_hours", "department", "purpose", "description"],
    "StudentService": ["name", "description"],
    "Housing": ["name", "location", "description"],
    "PreparatoryProgram": ["name", "duration", "description"],
}

AMOUNT_KEYS = {"display_amount", "amount_value", "currency", "amount_unit"}

DIRECT_ANSWER_KEYS = {
    "display_amount",
    "amount_value",
    "discount_percent",
    "valid_until",
    "payment_condition",
    "phone",
    "email",
    "whatsapp",
    "fax",
    "office_hours",
    "duration",
    "credits",
    "study_days",
    "study_format",
    "career_fields",
    "contact",
    "service",
    "faculty",
    "preparatory_program",
    "document",
    "required_for",
    "prepares_for",
    "specialization",
    "requirement",
    "requirement_text",
    "requirement_type",
    "criteria_logic",
    "bagrut_average_min",
    "psychometric_min",
    "combined_score_min",
    "math_units",
    "math_grade_min",
    "physics_units",
    "physics_grade_min",
    "hebrew_score_min",
    "deadline",
    "conditions",
    "unit_type",
    "housing",
    "parking",
    "campus",
}

TITLE_DISPLAY_OVERRIDES = {
    "כולל_נלוות_מחירון_מעונות_תשפז": "מחירון מעונות כולל תשלומים נלווים לשנת תשפ\"ז",
    "נלוות_מחירון_מעונות_תשפז": "תשלומים נלווים במעונות לשנת תשפ\"ז",
}
